alias aptg='sudo apt-get install'
alias apti='sudo apt-cache show'
alias apts='sudo apt-cache search'
alias gits='git status'
alias gitl='git log --pretty=fuller --stat --no-merges'
alias vi='vim -b'
alias grep='grep --colour=auto'
alias rgrep='rgrep --colour=auto'
alias pandoc='pandoc -t plain'
alias qscp='scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
alias qssh='ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
